‹
echo-karriere/frontend pull request #10
Opened 2020-10-26 17:13 UTC by mVabo

Dashboard dummy made at /dashboard

Routing changed, removed general styling and put it to specific files.

2020-10-27 15:48 UTC, sondr3 requested changes
Ser overall bra ut, har lagt igjen noen kommentarer på bruk av TypeScript og litt på event handlers :+1:

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/components/Title.tsx
> +};
Vi trenger ikke `propTypes` når vi bruker TypeScript, man bruker heller interfaces:

```ts
interface Props:
    children: React.ReactNode;
}

export default function Title({ children }: Props) {
```

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/components/Orders.tsx
> +function createData(id, date, name, shipTo, paymentMethod, amount) {
```suggestion
function createData(id: number, date: string, name: string, shipTo: string, paymentMethod: string, amount: number) {
```

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/components/Orders.tsx
> +function preventDefault(event) {
```suggestion
function preventDefault(event: MouseEvent) {
```

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/components/Information.tsx
> +function preventDefault(event: { preventDefault: () => void }) {
Liker at du har gjort dette på flere forskjellige måter :smile: Se under for et forslag.

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/components/Chart.tsx
> +function createData(time, amount) {
```suggestion
function createData(time: string, amount: number) {
```

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/Dashboard.tsx
> +  };
Disse funksjonene er litt overflødige, der du setter dette i JSXen kan du heller gjøre f.eks.:

```tsx
<IconButton onClick={() => setOpen(!open)}>
```

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/Dashboard.tsx
> +
Denne er jo duplisert nå, importer den heller fra `./Copyright.tsx`.

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/Dashboard.tsx
> +      <CssBaseline />
Denne er allerede satt i `./index.tsx`, ikke sett den her.

2020-10-27 15:48 UTC, sondr3 commented on src/views/dashboard/Dashboard.tsx
> +import clsx from "clsx";
Om vi bruker denne burde vi installere den i `package.json` og ikke være avhengige av at den kommer gjennom `@material-ui/core`. Litt overraska over at ESLint ikke klager :thinking:

2020-10-31 21:00 UTC, mVabo commented
I cry every time :(

2020-10-31 22:30 UTC, sondr3 commented
Tror det er fordi du la til `clsx` uten å faktisk installere den med `yarn` :)

2020-11-01 11:59 UTC, merged